{"name": "Create user where one of the fields has invalid data", "status": "passed", "parameters": [{"name": "user_data", "value": "{'email': 'sam422@gmail.com', 'password': '', 'name': 'Sam'}"}], "start": 1727745325556, "stop": 1727745325812, "uuid": "77744139-5b4e-4700-ae43-3217b658878b", "historyId": "10dbf13b308d2df15679c93947d74499", "testCaseId": "097b98d45b92e290e2b047ca8ae14df0", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_with_invalid_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "mac.lan"}, {"name": "thread", "value": "31983-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}